import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const mySchema = appSchema({
  version: 40,
  tables: [
    // ==================
    // 1. USUARIOS Y PERMISOS
    // ==================
    tableSchema({
      name: "perfiles",
      columns: [
        { name: "usuario", type: "string", isOptional: true },
        { name: "estado", type: "boolean" },
        { name: "hash_local", type: "string", isOptional: true },
        { name: "device_id", type: "string", isOptional: true },
        { name: "last_online_at", type: "number", isOptional: true },
        { name: "offline_ttl_hours", type: "number", isOptional: true },
        { name: "cached_permissions_json", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "informacion_perfil",
      columns: [
        { name: "nombres", type: "string", isOptional: true },
        { name: "ape_paterno", type: "string", isOptional: true },
        { name: "ape_materno", type: "string", isOptional: true },
        { name: "correo", type: "string" },
        { name: "rol", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "permisos",
      columns: [
        { name: "inventario", type: "boolean" },
        { name: "clientes", type: "boolean" },
        { name: "facturas", type: "boolean" },
        { name: "precios", type: "boolean" },
        { name: "usuarios", type: "boolean" },
        { name: "configuraciones", type: "boolean" },
        { name: "borrar", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sesiones_dispositivo",
      columns: [
        { name: "perfil_id", type: "string", isIndexed: true },
        { name: "device_id", type: "string" },
        { name: "device_name", type: "string", isOptional: true },
        { name: "last_online_at", type: "number" },
        { name: "offline_ttl_hours", type: "number" },
        { name: "is_active", type: "boolean" },
        { name: "revoked_at", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),

    // ==================
    // 2. CATÁLOGOS INDEPENDIENTES
    // ==================
    tableSchema({
      name: "familias",
      columns: [
        { name: "codigo_familia", type: "string" },
        { name: "nombre", type: "string" },
        { name: "estado", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "impuestos",
      columns: [
        { name: "nombre", type: "string" },
        { name: "tasa", type: "number" },
        { name: "activo", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "almacenes",
      columns: [
        { name: "nombre", type: "string" },
        { name: "estado", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "margenes",
      columns: [
        { name: "nombre", type: "string" },
        { name: "porcentaje", type: "number" },
        { name: "estado", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "proveedores",
      columns: [
        { name: "nombre_comercial", type: "string" },
        { name: "razon_social", type: "string", isOptional: true },
        { name: "rfc", type: "string", isOptional: true },
        { name: "telefono", type: "string", isOptional: true },
        { name: "correo_contacto", type: "string", isOptional: true },
        { name: "estado", type: "boolean" },
        { name: "_version", type: "number" },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "categorias_clientes",
      columns: [
        { name: "nombre", type: "string" },
        { name: "estado", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "clientes",
      columns: [
        { name: "nombre", type: "string" },
        { name: "rfc", type: "string", isOptional: true },
        { name: "categoria", type: "string", isOptional: true },
        { name: "lista_precio_base", type: "string" },
        { name: "descuento_global", type: "number" },
        { name: "contacto", type: "string", isOptional: true },
        { name: "calle", type: "string", isOptional: true },
        { name: "colonia", type: "string", isOptional: true },
        { name: "cp", type: "string", isOptional: true },
        { name: "ciudad", type: "string", isOptional: true },
        { name: "estado", type: "boolean" },
        { name: "_version", type: "number" },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "contactos",
      columns: [
        { name: "cliente_id", type: "string", isIndexed: true },
        { name: "contenido", type: "string" },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "proveedor_contactos",
      columns: [
        { name: "proveedor_id", type: "string", isIndexed: true },
        { name: "nombre", type: "string" },
        { name: "telefono", type: "string", isOptional: true },
        { name: "correo", type: "string", isOptional: true },
        { name: "cargo", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "precios_especiales_familias_clientes",
      columns: [
        { name: "cliente_id", type: "string", isIndexed: true },
        { name: "familia_id", type: "string", isIndexed: true },
        { name: "descuento_porcentaje", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),

    // ==================
    // 3. PRODUCTOS Y DEPENDENCIAS
    // ==================
    tableSchema({
      name: "productos",
      columns: [
        { name: "familia_id", type: "string", isIndexed: true },
        {
          name: "margen_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "codigo_interno", type: "string" },
        { name: "descripcion", type: "string" },
        { name: "precio_lista", type: "number" },
        { name: "precio_mayoreo", type: "number" },
        { name: "precio_menudeo", type: "number" },
        { name: "costo_base", type: "number" },
        { name: "ultimo_costo_base", type: "number" },
        { name: "clave_sat", type: "string", isOptional: true },
        { name: "imagen", type: "string", isOptional: true },
        { name: "estado", type: "boolean" },
        { name: "umbral_verde_dias", type: "number" },
        { name: "umbral_amarillo_dias", type: "number" },
        { name: "umbral_rojo_dias", type: "number" },
        { name: "_version", type: "number" },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "producto_impuestos",
      columns: [
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "impuesto_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "codigos_alternos",
      columns: [
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "codigo_barras", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "lotes",
      columns: [
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "identificador_lote", type: "string" },
        { name: "unidad_medida", type: "string" },
        { name: "costo_adquisicion", type: "number" },
        { name: "fecha_caducidad", type: "number", isOptional: true },
        { name: "estado", type: "boolean" },
        { name: "cantidad", type: "number" },
        { name: "_version", type: "number" },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "proveedor_productos",
      columns: [
        { name: "proveedor_id", type: "string", isIndexed: true },
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "codigo_proveedor", type: "string", isOptional: true },
        { name: "precio_compra", type: "number" },
        { name: "tiempo_entrega_dias", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "precios_especiales_clientes",
      columns: [
        { name: "cliente_id", type: "string", isIndexed: true },
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "descuento_porcentaje", type: "number" },
        { name: "precio_fijo", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),

    // ==================
    // 4. TRANSACCIONES E INVENTARIO
    // ==================
    tableSchema({
      name: "movimientos_inventario",
      columns: [
        { name: "almacen_id", type: "string", isIndexed: true },
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "lote_id", type: "string", isIndexed: true, isOptional: true },
        { name: "usuario_id", type: "string", isIndexed: true },
        {
          name: "documento_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "tipo", type: "string" },
        { name: "cantidad", type: "number" },
        { name: "cantidad_anterior", type: "number" },
        { name: "cantidad_posterior", type: "number" },
        { name: "referencia", type: "string", isOptional: true },
        { name: "device_id", type: "string", isOptional: true },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "documentos",
      columns: [
        { name: "cliente_id", type: "string", isIndexed: true },
        { name: "usuario_id", type: "string", isIndexed: true },
        { name: "tipo", type: "string" },
        { name: "folio", type: "string", isOptional: true },
        { name: "estado", type: "string" },
        { name: "subtotal", type: "number" },
        { name: "total_impuestos", type: "number" },
        { name: "total", type: "number" },
        { name: "_version", type: "number" },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "documentos_detalles",
      columns: [
        { name: "documento_id", type: "string", isIndexed: true },
        { name: "producto_id", type: "string", isIndexed: true },
        { name: "cantidad", type: "number" },
        { name: "descripcion_aplicada", type: "string", isOptional: true },
        { name: "precio_unitario_aplicado", type: "number" },
        { name: "descuento_aplicado", type: "number" },
        { name: "json_impuestos_aplicados", type: "string", isOptional: true },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "operaciones_documento",
      columns: [
        { name: "documento_id", type: "string", isIndexed: true },
        { name: "tipo_operacion", type: "string" },
        { name: "usuario_id", type: "string" },
        { name: "device_id", type: "string", isOptional: true },
        { name: "motivo", type: "string", isOptional: true },
        { name: "monto", type: "number", isOptional: true },
        { name: "documento_relacionado_id", type: "string", isOptional: true },
        { name: "metadata_json", type: "string", isOptional: true },
        { name: "deleted", type: "boolean", isOptional: true },
        { name: "status", type: "string", isOptional: true },
        { name: "retry_count", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),

    // ==================
    // 5. AUDITORÍA Y ERRORES
    // ==================
    tableSchema({
      name: "bitacora_errores",
      columns: [
        { name: "tabla_origen", type: "string" },
        { name: "registro_id", type: "string", isIndexed: true },
        { name: "accion", type: "string" },
        { name: "payload_json", type: "string", isOptional: true },
        { name: "mensaje_error", type: "string" },
        { name: "estado", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "audit_log",
      columns: [
        { name: "tabla", type: "string", isIndexed: true },
        { name: "registro_id", type: "string", isIndexed: true },
        { name: "accion", type: "string" },
        { name: "usuario_id", type: "string", isIndexed: true },
        { name: "device_id", type: "string" },
        { name: "campos_cambiados", type: "string", isOptional: true },
        { name: "valores_anteriores", type: "string", isOptional: true },
        { name: "valores_nuevos", type: "string", isOptional: true },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),

    // ==================
    // 6. CONFIGURACIONES
    // ==================
    tableSchema({
      name: "invoice_templates",
      columns: [
        { name: "name", type: "string" },
        { name: "layout_json", type: "string" },
        { name: "is_default", type: "boolean" },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "plantillas_precios",
      columns: [
        { name: "nombre", type: "string" },
        { name: "estado", type: "boolean" },
        { name: "_version", type: "number" },
        { name: "updated_by", type: "string", isOptional: true },
        { name: "updated_device", type: "string", isOptional: true },
        { name: "deleted_at", type: "number", isOptional: true },
        { name: "deleted_by", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "reglas_plantilla",
      columns: [
        { name: "plantilla_id", type: "string", isIndexed: true },
        { name: "tipo", type: "string" },
        { name: "target_id", type: "string" },
        { name: "descuento_porcentaje", type: "number" },
        { name: "precio_fijo", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "clientes_plantillas",
      columns: [
        { name: "cliente_id", type: "string", isIndexed: true },
        { name: "plantilla_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),

    // ==================
    // 7. DIAGNÓSTICO Y CACHÉ LOCAL
    // ==================
    tableSchema({
      name: "sync_journal",
      columns: [
        { name: "sync_id", type: "string" },
        { name: "direction", type: "string" },
        { name: "status", type: "string" },
        { name: "tables_affected", type: "string" },
        { name: "records_pulled", type: "number" },
        { name: "records_pushed", type: "number" },
        { name: "records_rejected", type: "number" },
        { name: "conflicts_detected", type: "number" },
        { name: "duration_ms", type: "number" },
        { name: "error_message", type: "string", isOptional: true },
        { name: "device_id", type: "string" },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "stats_cache",
      columns: [
        { name: "fecha", type: "string" },
        { name: "tipo_metrica", type: "string" },
        { name: "valor", type: "number" },
        { name: "created_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "tombstones",
      columns: [
        { name: "table_name", type: "string" },
        { name: "record_id", type: "string", isIndexed: true },
        { name: "deleted_at", type: "number" },
      ],
    }),
  ],
});
