CREATE OR REPLACE FUNCTION public.pull_changes(last_pulled_at BIGINT DEFAULT 0) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $fn$
DECLARE _st BIGINT; _r JSONB;
BEGIN
_st:=(EXTRACT(EPOCH FROM NOW())*1000)::BIGINT;
_r:=jsonb_build_object('changes',jsonb_build_object(
'perfiles',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'usuario',usuario,'estado',estado,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'hash_local',hash_local)),'[]'::jsonb) FROM public.perfiles WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'usuario',usuario,'estado',estado,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'hash_local',hash_local)),'[]'::jsonb) FROM public.perfiles WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'informacion_perfil',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombres',nombres,'ape_paterno',ape_paterno,'ape_materno',ape_materno,'correo',correo,'rol',rol,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.informacion_perfil WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombres',nombres,'ape_paterno',ape_paterno,'ape_materno',ape_materno,'correo',correo,'rol',rol,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.informacion_perfil WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'permisos',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'inventario',inventario,'clientes',clientes,'facturas',facturas,'precios',precios,'usuarios',usuarios,'configuraciones',configuraciones,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.permisos WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'inventario',inventario,'clientes',clientes,'facturas',facturas,'precios',precios,'usuarios',usuarios,'configuraciones',configuraciones,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.permisos WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'familias',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'codigo_familia',codigo_familia,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'umbral_verde_dias',umbral_verde_dias,'umbral_amarillo_dias',umbral_amarillo_dias,'umbral_rojo_dias',umbral_rojo_dias)),'[]'::jsonb) FROM public.familias WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'codigo_familia',codigo_familia,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'umbral_verde_dias',umbral_verde_dias,'umbral_amarillo_dias',umbral_amarillo_dias,'umbral_rojo_dias',umbral_rojo_dias)),'[]'::jsonb) FROM public.familias WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'impuestos',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'tasa',tasa,'activo',activo,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.impuestos WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'tasa',tasa,'activo',activo,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.impuestos WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'almacenes',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.almacenes WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.almacenes WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'margenes',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'porcentaje',porcentaje,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.margenes WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'porcentaje',porcentaje,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.margenes WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'proveedores',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre_comercial',nombre_comercial,'razon_social',razon_social,'rfc',rfc,'telefono',telefono,'correo_contacto',correo_contacto,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.proveedores WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre_comercial',nombre_comercial,'razon_social',razon_social,'rfc',rfc,'telefono',telefono,'correo_contacto',correo_contacto,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.proveedores WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'categorias_clientes',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.categorias_clientes WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.categorias_clientes WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'clientes',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'lista_precio_base',lista_precio_base,'descuento_global',descuento_global,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'rfc',rfc,'categoria',categoria,'contacto',contacto,'calle',calle,'colonia',colonia,'cp',cp,'ciudad',ciudad)),'[]'::jsonb) FROM public.clientes WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'nombre',nombre,'lista_precio_base',lista_precio_base,'descuento_global',descuento_global,'estado',estado,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT,'rfc',rfc,'categoria',categoria,'contacto',contacto,'calle',calle,'colonia',colonia,'cp',cp,'ciudad',ciudad)),'[]'::jsonb) FROM public.clientes WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb),
'contactos',jsonb_build_object('created',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'cliente_id',cliente_id,'contenido',contenido,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.contactos WHERE (EXTRACT(EPOCH FROM created_at)*1000)>last_pulled_at),'updated',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',id,'cliente_id',cliente_id,'contenido',contenido,'created_at',(EXTRACT(EPOCH FROM created_at)*1000)::BIGINT,'updated_at',(EXTRACT(EPOCH FROM updated_at)*1000)::BIGINT)),'[]'::jsonb) FROM public.contactos WHERE (EXTRACT(EPOCH FROM updated_at)*1000)>last_pulled_at AND (EXTRACT(EPOCH FROM created_at)*1000)<=last_pulled_at),'deleted','[]'::jsonb)
),'timestamp',_st);
RETURN _r;
END;$fn$;
